### DISCUSSION TITLE
CssMinimizerPlugin removes asterisk from css selector

### DISCUSSION THREAD

**Discussion by nonick891** [webpack/webpack#15223] [Q&A] [answered]
Hey guys,

Comment is pretty self explanatory. Asterisk (*) sign is removed not just from comments but from selector.

The next css code:

``` css
  *:where(:not(iframe, canvas, img, svg, video):not(svg *, symbol *)) {
	  all: unset;
	  display: revert;
  }
  
  *,
  *::before,
  *::after {
	  box-sizing: border-box;
  }
```

transpiling into:

``` css
:where(:not(iframe,canvas,img,svg,video):not(svg *,symbol *)){all:unset;display:revert}*,:after,:before{box-sizing:border-box}
```

``` js
module.exports = {
	...
	module: {
		rules: [
			...
			{
				test: /\.s[ac]ss$/i,
				use: [
					MiniCssExtractPlugin.loader,
					'css-loader',
					{
						loader: 'sass-loader',
						options: {
							implementation: require('sass'),
							sassOptions: { fiber: false }
						}
					}
				]
			}
		]
	},
	optimization: {
		minimize: process.env.npm_lifecycle_event === 'build',
		minimizer: [new CssMinimizerPlugin()],
	},
	plugins: [
		new MiniCssExtractPlugin({
			filename: '[name].min.css',
			chunkFilename: '[id].css'
		}),
		...
	]
}

```

Am I doing something wrong?
