### DISCUSSION TITLE
Will `experiments.css` supports `@import './foo.css' print` in the future?

### DISCUSSION THREAD

**Discussion by hyf0** [webpack/webpack#15995] [General]
I currently use `mini-css-extract-plugin` but want to migrate to `experiments.css`.

**Comment by alexander-akait** [comment]
I think it already suppports it

**Reply by hyf0** [reply]
It compiles. But the output seems to be not expected.

![image](https://user-images.githubusercontent.com/49502170/176342859-33c23223-f72a-491c-92ee-7297ff83a179.png)

The expected output  should be 
```css
@media print {
  .a {
    background-repeat: no-repeat;
  }
}
```

```
$ yarn webpack --version
webpack: 5.73.0
webpack-cli: 4.9.2
webpack-dev-server 4.9.0
```
