### DISCUSSION TITLE
Leaflet map does not show up in webpack setup

### DISCUSSION THREAD

**Discussion by kees-closed** [webpack/webpack#16263] [Q&A] [answered]
I'm trying to get a webpack project going with Leaflet. However, the map doesn't show up. My guess is because the CSS is not loaded. Can someone point me in the right direction here?

https://github.com/kees-closed/TZM-Chapters-Map/tree/dev

**Comment by alexander-akait** [comment, marked as answer]
Uncomment `import "./index.css";`

and put this:

```css
.leaflet-container {
        width: 500px;
        height: 500px;
        font-size: 20px;
        font-family: 'Poppins', Helvetica;
        text-transform: uppercase;
}
```

You need to set width and height
