### DISCUSSION TITLE
Cannot add additionalData to .scss files in my Vue project.

### DISCUSSION THREAD

**Discussion by Nathan7139** [webpack/webpack#17660] [Q&A]
I'm coding with Vue and SCSS. For some reason, I want to use an environment variable in a .scss file. There is much discussion about [how to use an environment variable in an SCSS block in a .vue file](https://github.com/vercel/next.js/discussions/19042#discussioncomment-126507). But it will not work with a .scss file. Could anyone tell me how to do that?

[Here](https://github.com/Nathan7139/vue-sass-loader-issue) is a minimal reproducible example of my question. You can use `npm install` for install and use `npm run serve` to testing.

In file `src/App.vue`, I use `$test` to set color and it work fine.
In file `src/style.scss`, if I use `$test`, it will indicate that `$test` is an undefined variable.
```scss
div {
  font-size: 100px;

  // error  in ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=scss
  
  //   Syntax Error: SassError: Undefined variable.
  //    ╷
  // 14 │   @if $test == 'a' {
  //    │       ^^^^^
  //    ╵
  //   src/style.scss 14:7  @use
  //   src/App.vue 1:1      root stylesheet

  @if $test == 'a' {
    background-color: blue;
  } @else if $test == 'apple' {
    background-color: green;
  } @else {
    background-color: yellow;
  }
}
```
So additionalData work for .vue file but not .scss fils. I wonder is there a simple way to use an environment variable in a .scss file?
