### DISCUSSION TITLE
I can't use mini-css-extract-plugin and exportLocalsConvention: "asIs"

### DISCUSSION THREAD

**Discussion by TheAlexGo** [webpack/webpack#18032] [Q&A]
Hi all! Please help me figure it out: is it possible to use mini-css-extract-plugin together with exportLocalsConvention: "asIs" (for css-modules)? I didn’t find the answer anywhere in the documentation, but I need just such a bundle.

### My webpack config:
```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const path = require("path");

const isProd = process.env.BUILD_MODE === 'prod';

module.exports = {
  mode: isProd ? 'production' : "development",
  entry: "./src/Button.tsx",
  output: {
    path: path.join(__dirname, "dist"),
    clean: true,
  },
  module: {
    strictExportPresence: true,
    rules: [
      {
        test: /\.(ts|tsx)$/,
        use: "babel-loader",
        exclude: /node_modules/,
      },
      {
        test: /\.module.css$/,
        use: [
          MiniCssExtractPlugin.loader
          {
            loader: "css-loader",
            options: {
              esModule: true,
              modules: {
                namedExport: true,
                exportLocalsConvention: "asIs"
              },
            },
          },
        ],
      },
    ],
  },
  plugins: [new MiniCssExtractPlugin()],
  resolve: {
    extensions: [".ts", ".tsx", ".js"],
  },
};
```

### The error I get is
<img width="596" alt="image" src="https://github.com/webpack/webpack/assets/59894219/935d9f84-d588-45fc-bba4-9c2e7c4af718">

### My css
```css
.button {
  color: #f00;
  padding: 10px;
  font-size: 18px;
}

.test {
  display: inline;
}

.button-test {
  display: block;
}

.button-aboba {
  display: inline;
}

.button_dashes {
  display: block;
}

.button-test__input {
  display: inline;
}
```

### My test component
```JSX
import { FC } from "react";
import * as classes from "./Button.module.css";

export const Button: FC = (props) => {
  return <button {...props} className={classes['button-aboba']} />;
};
```
