### ISSUE TITLE
Unable to ignore image in css file

### ISSUE THREAD

**Issue by SimenB** [webpack/webpack#1039]
I'd like to ignore the following imports in a (vendor) css file

``` css
table.dataTable thead .sorting {
  background: url("../images/sort_both.png") no-repeat center right;
}
table.dataTable thead .sorting_asc {
  background: url("../images/sort_asc.png") no-repeat center right;
}
table.dataTable thead .sorting_desc {
  background: url("../images/sort_desc.png") no-repeat center right;
}
table.dataTable thead .sorting_asc_disabled {
  background: url("../images/sort_asc_disabled.png") no-repeat center right;
}
table.dataTable thead .sorting_desc_disabled {
  background: url("../images/sort_desc_disabled.png") no-repeat center right;
}
```

These rules are overwritten later, so shouldn't be an issue if the images 404.

Config is

``` js
new webpack.IgnorePlugin(/\.\.\/images\/sort_[a-z]+(_disabled)?\.png$/, /vendor$/)
```

(If you can give me a cleaner regex, that'd be much appreciated :smile:)

Error is

```
ERROR in ./common-assets/src/assets/styles/common.css
Module build failed: Error: Cannot find module "../images/sort_both.png"
```

(`common.css` does `@import url("vendor/jquery.dataTables.css");`, probably the reason that's the filename).

I debugged a bit, and it seems to enter the correct place in the `IgnorePlugin`, but I still get an error.

![image](https://cloud.githubusercontent.com/assets/1404810/7468649/577cd300-f30b-11e4-95bc-2fdeb3a2abe9.png)

Doing 

``` js
new webpack.NormalModuleReplacementPlugin(/\.\.\/images\/sort_[a-z]+(_disabled)?\.png$/, 'node-noop')
```

Works, but leaves `[object Object]` in the import, which is kinda ugly (the reason for https://github.com/webpack/extract-text-webpack-plugin/issues/65)
