### ISSUE TITLE
CSS module @keyframes not hashed correctly in bundle depending on keyframe naming !

### ISSUE THREAD

**Issue by blephy** [webpack/webpack#11568]
# Bug report

**What is the current behavior?**

When using css module feature, keyframes hash are not parsed correctly in production build depending on their name .
The bug does not appear in development mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can experiment the behavior [in this repository](https://github.com/blephy/allandolle-portfolio/pull/37)

```scss
/// scss file home.module.scss
.title {
  letter-spacing: 0.4em;
  margin-bottom: 32px;
  margin-left: 32px;
}

.signature {
  width: 100px;

  path {
    animation: draw 3.3s ease-in-out forwards;
    stroke: #fff;
    stroke-dasharray: 450;
    stroke-dashoffset: 450;
  }

  circle {
    animation: draw-circle 0.25s ease-in 1.5s forwards;
  }
}

@keyframes draw {
  to {
    stroke-dashoffset: 0;
  }
}

@keyframes draw-circle {
  from {
    fill: #fff;
    opacity: 0;
  }

  to {
    fill: #fff;
    opacity: 1;
  }
}
```

```ts
/** tsx file home.tsx */
import React from 'react'
import { Helmet } from 'react-helmet'
import { RouteComponentProps } from 'react-router-dom'

import { ReactComponent as Signature } from '@/images/signature.svg'

import styles from './home.module.scss'

type TMatch = {
  path: string
}

export default function Home({
  match
}: RouteComponentProps<TMatch>): React.FunctionComponentElement<RouteComponentProps> {
  const { path } = match
  const canonicalUrl = `${process.env.SERVER_BASE_URL}${path}`

  return (
    <>
      <Helmet>
        <title>Analyst developer</title>
        <link rel='canonical' href={canonicalUrl} />
        <meta name='description' content='Welcome to my portfolio' />
      </Helmet>
      <h1 className={styles.title}>Allan Doll&eacute;</h1>
      <Signature className={styles.signature} />
    </>
  )
}
```

```ts
/** webpack.prod.ts */
import CircularDependencyPlugin from 'circular-dependency-plugin'
import { CleanWebpackPlugin } from 'clean-webpack-plugin'
import CopyWebpackPlugin from 'copy-webpack-plugin'
import CssMinimizerPlugin from 'css-minimizer-webpack-plugin'
import { config } from 'dotenv'
import HtmlWebPackPlugin from 'html-webpack-plugin'
import MiniCssExtractPlugin from 'mini-css-extract-plugin'
import path from 'path'
import postcssNormalize from 'postcss-normalize'
import PreloadWebpackPlugin from 'preload-webpack-plugin'
import ScriptExtHtmlWebpackPlugin from 'script-ext-html-webpack-plugin'
import SitemapPlugin from 'sitemap-webpack-plugin'
import StylelintPlugin from 'stylelint-webpack-plugin'
import TerserPlugin from 'terser-webpack-plugin'
import webpack from 'webpack'

config()

const serverBaseUrl = process.env.HTTPS ? `https://${process.env.DOMAIN_NAME}` : `http://${process.env.DOMAIN_NAME}`

const sitemapPaths = [
  {
    path: '/',
    priority: '0.8'
  }
]

const rootDir = path.join(__dirname, '..', '..')

module.exports = {
  target: 'web',
  name: 'production',
  mode: 'production',
  context: path.resolve(rootDir, 'src'),
  bail: true,
  entry: {
    app: path.resolve(rootDir, 'src/index.tsx')
  },
  stats: {
    assets: true,
    entrypoints: true,
    chunks: true,
    modules: true,
    builtAt: true,
    hash: true
  },
  output: {
    path: path.resolve(rootDir, 'build'),
    filename: '[name].[contenthash].js',
    chunkFilename: 'js/[name].[contenthash].chunk.js',
    publicPath: '/',
    crossOriginLoading: 'anonymous',
    chunkLoadTimeout: 20000,
    pathinfo: false
  },
  devtool: 'none',
  resolve: {
    extensions: ['*', '.js', '.jsx', '.ts', '.tsx', '.css', '.scss'],
    modules: ['src', 'node_modules'],
    alias: {
      '@': path.resolve(rootDir, 'src')
    }
  },
  optimization: {
    mergeDuplicateChunks: true,
    flagIncludedChunks: true,
    occurrenceOrder: true,
    namedChunks: true,
    namedModules: true,
    runtimeChunk: {
      name: (entrypoint: { name: string }) => `runtime~${entrypoint.name}`
    },
    minimize: true,
    minimizer: [
      new TerserPlugin({
        cache: true,
        parallel: true,
        sourceMap: false,
        extractComments: false,
        terserOptions: {
          output: {
            comments: false
          }
        }
      }),
      new CssMinimizerPlugin({
        sourceMap: false,
        minimizerOptions: {
          preset: [
            'default',
            {
              discardComments: { removeAll: true }
            }
          ]
        }
      })
    ],
    splitChunks: {
      chunks: 'all',
      minSize: 25000,
      maxSize: 200000,
      minChunks: 1,
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      automaticNameDelimiter: '~',
      name: true,
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: 0
        },
        default: {
          priority: -1,
          reuseExistingChunk: true
        }
      }
    }
  },
  performance: {
    hints: 'error',
    maxEntrypointSize: 250000,
    maxAssetSize: 200000
  },
  plugins: [
    new CleanWebpackPlugin(),
    new CircularDependencyPlugin({
      exclude: /node_modules/,
      failOnError: true,
      allowAsyncCycles: true,
      cwd: process.cwd()
    }),
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 80,
      minChunkSize: 25000
    }),
    new webpack.HashedModuleIdsPlugin(),
    new HtmlWebPackPlugin({
      meta: {
        viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=yes',
        robots: 'noodp'
      },
      title: process.env.TITLE,
      preconnect: serverBaseUrl,
      template: path.resolve(rootDir, 'public/templates/index.ejs'),
      favicon: path.resolve(rootDir, 'public/favicon.png'),
      filename: 'index.html',
      minify: true,
      xhtml: true
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
      'process.env.HOST': JSON.stringify(process.env.HOST),
      'process.env.API_URL': JSON.stringify(process.env.API_URL),
      'process.env.DOMAIN_NAME': JSON.stringify(process.env.DOMAIN_NAME),
      'process.env.HTTPS': JSON.stringify(process.env.HTTPS),
      'process.env.SERVER_BASE_URL': JSON.stringify(serverBaseUrl),
      'process.env.CT_REPORT_URI': JSON.stringify(process.env.CT_REPORT_URI),
      'process.env.CSP_REPORT_URI': JSON.stringify(process.env.CSP_REPORT_URI),
      'process.env.APP_TITLE': JSON.stringify(process.env.APP_TITLE)
    }),
    new MiniCssExtractPlugin({
      filename: 'css/[name].[contenthash].css',
      chunkFilename: 'css/[id].[contenthash].chunk.css'
    }),
    new CopyWebpackPlugin({
      patterns: [
        {
          from: path.resolve(rootDir, 'public', 'humans.txt'),
          to: path.resolve(rootDir, 'build'),
          transform: (content: Buffer) => `${content.toString()}  Last update: ${new Date().toUTCString()}`
        },
        {
          from: path.resolve(rootDir, 'public', 'robots.txt'),
          to: path.resolve(rootDir, 'build'),
          transform: (content: Buffer) =>
            `${content.toString()}\r\n# Sitemap\r\nSitemap: ${serverBaseUrl}/.well-known/sitemap.xml\r\n`,
          cacheTransform: true
        },
        {
          from: path.resolve(rootDir, 'public', 'security.txt'),
          to: path.resolve(rootDir, 'build/.well-known'),
          cacheTransform: true
        }
      ]
    }),
    new PreloadWebpackPlugin({
      rel: 'preload',
      include: 'initial'
    }),
    new ScriptExtHtmlWebpackPlugin({
      sync: /^runtime.*\.js$/,
      defaultAttribute: 'async'
    }),
    new SitemapPlugin(serverBaseUrl, sitemapPaths, {
      filename: '.well-known/sitemap.xml',
      skipgzip: true,
      lastmod: true,
      priority: 0.5,
      changefreq: 'monthly'
    }),
    new StylelintPlugin()
  ],
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: 'eslint-loader'
      },
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true
          }
        }
      },
      {
        oneOf: [
          {
            test: /\.html$/,
            use: [
              {
                loader: 'html-loader',
                options: {
                  minimize: true,
                  removeComments: true,
                  collapseWhitespace: true
                }
              }
            ]
          },
          {
            test: /\.css$/,
            use: [
              MiniCssExtractPlugin.loader,
              { loader: 'css-loader', options: { importLoaders: 1 } },
              {
                loader: 'postcss-loader',
                options: {
                  postcssOptions: {
                    ident: 'postcss',
                    plugins: () => [postcssNormalize()]
                  }
                }
              }
            ]
          },
          {
            test: /\.scss$/,
            use: [
              MiniCssExtractPlugin.loader,
              { loader: 'css-loader', options: { importLoaders: 1 } },
              {
                loader: 'postcss-loader',
                options: {
                  postcssOptions: {
                    ident: 'postcss',
                    plugins: () => [postcssNormalize()]
                  }
                }
              },
              'sass-loader'
            ]
          },
          {
            test: /\.(woff|woff2|eot|ttf|otf)$/,
            use: {
              loader: 'file-loader',
              options: {
                emitFile: true,
                outputPath: 'fonts/',
                name: '[name].[hash].[ext]'
              }
            }
          },
          {
            test: /\.(png|jp(e*)g|gif)$/,
            use: {
              loader: 'url-loader',
              options: {
                limit: 8192,
                emitFile: true,
                outputPath: 'images/',
                name: '[name].[hash].[ext]'
              }
            }
          },
          {
            test: /\.svg$/,
            use: ['@svgr/webpack', 'url-loader']
          }
        ]
      }
    ]
  }
}
```

**What is the expected behavior?**

Webpack should produce an hash class selector matching the keyframe hash `draw` but it does not. 

Webpack produce this css file.  : 

```css
.QGoYhGzlQu7-Stf0Jgtjs{letter-spacing:.4em;margin-bottom:32px;margin-left:32px}._2f-763U9aR_m95TZkSTerd{width:100px}._2f-763U9aR_m95TZkSTerd path{animation:NaNjtcXwnmOr8f36q3l-8W 3.3s ease-in-out forwards;stroke:#fff;stroke-dasharray:450;stroke-dashoffset:450}._2f-763U9aR_m95TZkSTerd circle{animation:_2APW8yWcYXdDHglJ5UTsYC .25s ease-in 1.5s forwards}@keyframes e5jtcXwnmOr8f36q3l-8W{to{stroke-dashoffset:0}}@keyframes _2APW8yWcYXdDHglJ5UTsYC{0%{fill:#fff;opacity:0}to{fill:#fff;opacity:1}}
```

Look at the `path{animation:NaNjtcXwnmOr8f36q3l-8W` rule. NaN ? This should match the `e5jtcXwnmOr8f36q3l-8W` keyframe hash

If you rename the keyframe to draw-path the bug disappear and produce this css file, which works : 

```css
.QGoYhGzlQu7-Stf0Jgtjs{letter-spacing:.4em;margin-bottom:32px;margin-left:32px}._2f-763U9aR_m95TZkSTerd{width:100px}._2f-763U9aR_m95TZkSTerd path{animation:_1kK86ZIzEgrq-1wnstBKuz 3.3s ease-in-out forwards;stroke:#fff;stroke-dasharray:450;stroke-dashoffset:450}._2f-763U9aR_m95TZkSTerd circle{animation:_2APW8yWcYXdDHglJ5UTsYC .25s ease-in 1.5s forwards}@keyframes _1kK86ZIzEgrq-1wnstBKuz{to{stroke-dashoffset:0}}@keyframes _2APW8yWcYXdDHglJ5UTsYC{0%{fill:#fff;opacity:0}to{fill:#fff;opacity:1}}
```

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 12.18.3
Operating System: Mac OS Catalina 10.15.5
Additional tools: See webpack config.
