### ISSUE TITLE
Webpack cannot output global css when using mini-css-extract-plugin

### ISSUE THREAD

**Issue by duan602728596** [webpack/webpack#11708]
# Bug report

**What is the current behavior?**
When I compile in a production environment, I found that global css cannot be output, only css of css-modules can be output. This appeared in the webpack 5.1.1 version. When I used webpack 5.1.0, this problem did not occur.

For example, what should be output is:
```css
.app {
  color: #000;
}

._1NBoggxDtp1TrWNgYFXOtj {
  color: #f00;
}
```
But actually the output is:

```css
._1NBoggxDtp1TrWNgYFXOtj {
  color: #f00;
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Demo: [https://github.com/duan602728596/webpack-bug-demo](https://github.com/duan602728596/webpack-bug-demo)

**What is the expected behavior?**
The css file should contain css-modules css and global css.

**Other relevant information:**
webpack version: 5.1.1
Node.js version: 14.9.0
Operating System: macOS 10.15.6
Additional tools: yarn@1.22.5
