### ISSUE TITLE
Question: Suggestion: Webpack hard to build desired structure

### ISSUE THREAD

**Issue by thakerng** [webpack/webpack#1370]
If we have 
```
.
├── src
|   ├── css
|   |    └──  style.css
|   ├── images
|   |    └── image.png
|   └── js
|        └── main.js
.
```
```css
/* src/css/style.css*/
body{
   background:url(../images/image.png)
}
```
```javascript
/* src/js/main.js*/
require('../css/style.css')
```
I want compile to `dist` folder as the same structure like 
```
.
├── dist
|   ├── css
|   |    └──  main-bundle.css
|   ├── assets
|   |    └── image.png
|   └── js
|        └── main-bundle.js
├── src
.   └── ...
```
so we wrote webpack.config.js using ExtractTextPlugin to extract css file seperately like
```javascript
entry: {
    main:"main.js"
},
output: {
    path: path.join(__dirname, "dist"),
    filename: "./js/[name].bundle.js"
},
module: {
    loaders: [
        { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") },
        { test: /\.png$/, loader: "file-loader?name=./assets/[name].[ext]" }
    ],
    plugins: [
        new ExtractTextPlugin("./css/[name]-bundle.css")
    ]
}
```
So we got
```css
/* dist/css/main-bundle.css*/
body{
   background:url(./assets/image.png)
}
```
But actually ,we want it to be `url(../assets/image.png)` when I config png loader `file-loader?name=../images/[name].[ext]` it put the image file to outside dist folder instead. I have found out that it's impossible to set url correctly
