### ISSUE TITLE
Error in multithreading with wasm-pack and webassembly rust

### ISSUE THREAD

**Issue by iMplode-nZ** [webpack/webpack#14087]
# Bug report

**What is the current behavior?**

When compiling https://github.com/iMplode-nZ/rust-webpack-multithreading-test via `(p)npm watch` using webpack 5.49.0 and the latest rust and the rust flags `-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals`, I get this error:

```
webpack compiled with 1 error
ERROR in ./pkg/index_bg.wasm
Module parse failed: Unexpected section: 0xc
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Unexpected section: 0xc
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone https://github.com/iMplode-nZ/rust-webpack-multithreading-test, `npm install`, `npm serve`.

**What is the expected behavior?**

It does not error.

**Other relevant information:**
webpack version:  5.49.0
Node.js version: 14.4.0
Operating System: Ubuntu 20.04 focal
Additional tools:
```
rustc 1.56.0-nightly (4e282795d 2021-07-31)
wasm-bindgen 0.2.75
wasm-pack 0.10.0
```

I'm putting this here as it seems more like a webpack bug than a wasm-pack/bindgen/rust bug.
See wasm-pack issue at https://github.com/rustwasm/wasm-pack/issues/1050

**Comment by mattzque** [comment]
Same issue here

"Unexpected section: 0xc" throws in [wasm-async](https://github.com/webpack/webpack/blob/main/lib/wasm-async/AsyncWebAssemblyParser.js#L48), or more precisely it crashes in [@webassemblyjs/wasm-parser](https://github.com/xtuc/webassemblyjs/blob/master/packages/wasm-parser/src/decoder.js#L1713). This is a minimal example to reproduce the error:

```
const { decode } = require("@webassemblyjs/wasm-parser");
const fs = require('fs');

decode(fs.readFileSync('file.wasm'), {
  ignoreCodeSection: true,
  ignoreDataSection: true,
  ignoreCustomNameSection: true,
})
```

example files to reproduce:
[wasm_parse_bug.zip](https://github.com/rustwasm/wasm-pack/files/7587631/wasm_parse_bug.zip)

**Comment by alexander-akait** [comment]
@xtuc Can you look at this?

**Comment by vankop** [comment]
probably some `target-feature` not supported  by current `@webassemblyjs/wasm-parser`

**Comment by maxammann** [comment]
I'm compiling with the following flags:

```toml
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
    # Enables features which are required for shared-memory
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # Enables the possibility to import memory into wasm.
    # Without --shared-memory it is not possible to use shared WebAssembly.Memory.
    "-C", "link-args=--shared-memory --import-memory",
]
```

If I import wasm via bindings generated by wasm_bindgen (`wasm-bindgen --target web --out-dir web target/wasm32-unknown-unknown/debug/mapr.wasm`) it works. The the bundle which was created by wasm-pack is improte dI get the above error.

**Comment by TimoWilhelm** [comment]
Same issue here with `rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]`. I tried both webassembly/async and webassembly/sync.

**Comment by maxammann** [comment]
For me everything works now, if you want I could provide you with webpack/rust configs.

**Comment by iMplode-nZ** [comment]
@maxammann Yes please.

**Comment by maxammann** [comment]
`.cargo/config.toml`

```toml
[build]
target = "x86_64-unknown-linux-gnu"

[target.wasm32-unknown-unknown]
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
    # Enables features which are required for shared-memory
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    # Enables the possibility to import memory into wasm.
    # Without --shared-memory it is not possible to use shared WebAssembly.Memory.
    "-C", "link-args=--shared-memory --import-memory",
]
```

A build script which does not use webpack. (get this working first!)

```bash
#!/bin/bash
set -e

webgl_flag=""

TEMP=$(getopt --long -o "g" "$@")
eval set -- "$TEMP"
while true; do
  case "$1" in
  -g)
    webgl_flag="web-webgl,"
    shift 2
    ;;
  *)
    break
    ;;
  esac
done

export RUSTUP_TOOLCHAIN=nightly-2022-02-26-x86_64-unknown-linux-gnu

rustup component add rust-src --toolchain nightly-2022-02-26-x86_64-unknown-linux-gnu

function plain_build() {
  cargo build --features "$webgl_flag" --target wasm32-unknown-unknown -Z build-std=std,panic_abort
  # TODO: Untested: --reference-types
  wasm-bindgen --target web --out-dir dist/mapr-pain-bindgen target/wasm32-unknown-unknown/debug/mapr.wasm
}

function wasm_pack_build() {
  ~/Downloads/wasm-pack-v0.10.1-x86_64-unknown-linux-musl/wasm-pack build . \
        --release --target web --out-dir dist/mapr -- \
        --features "$webgl_flag" -Z build-std=std,panic_abort
}

wasm_pack_build
```


My webpack config (not ready for copy&paste):


```js
const path = require("path");
const webpack = require("webpack");
const CopyPlugin = require("copy-webpack-plugin");
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");

let dist = path.join(__dirname, 'dist/demo');
module.exports = (env) => ({
    mode: "development",
    entry: {
        index: "./index.ts",
        'service-worker': "./service-worker.ts",
    },
    experiments: {
        syncWebAssembly: true
    },
    performance: {
        maxEntrypointSize: 400000,
        maxAssetSize: 400000000,
    },
    output: {
        path: dist,
        filename: "[name].js"
    },
    devServer: {
        server: {
            type: 'http',
        },
        allowedHosts: 'all',
        host: '0.0.0.0',
        static: {
            directory: dist,
        },
        headers: {
            'Cross-Origin-Opener-Policy': 'same-origin',
            'Cross-Origin-Embedder-Policy': 'require-corp'
        },
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
        ],
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    plugins: [
        new webpack.DefinePlugin({
            WEBGL: !!env.webgl
        }),
        new CopyPlugin({
            patterns: [
                {from: "static", to: "."},
            ],
        }),
        new WasmPackPlugin({
            crateDirectory: path.resolve(__dirname, '../'),

            // Check https://rustwasm.github.io/wasm-pack/book/commands/build.html for
            // the available set of arguments.
            //
            // Optional space delimited arguments to appear before the wasm-pack
            // command. Default arguments are `--verbose`.
            //args: '--log-level warn',
            // Default arguments are `--typescript --target browser --mode normal`.
            extraArgs: `--target web -- ${env.webgl ? '--features web-webgl' : ''} -Z build-std=std,panic_abort`,

            // Optional array of absolute paths to directories, changes to which
            // will trigger the build.
            // watchDirectories: [
            //   path.resolve(__dirname, "another-crate/src")
            // ],

            // The same as the `--out-dir` option for `wasm-pack`
            outDir: path.resolve(__dirname, 'dist/libs/mapr'),

            // The same as the `--out-name` option for `wasm-pack`
            // outName: "index",

            // If defined, `forceWatch` will force activate/deactivate watch mode for
            // `.rs` files.
            //
            // The default (not set) aligns watch mode for `.rs` files to Webpack's
            // watch mode.
            // forceWatch: true,

            // If defined, `forceMode` will force the compilation mode for `wasm-pack`
            //
            // Possible values are `development` and `production`.
            //
            // the mode `development` makes `wasm-pack` build in `debug` mode.
            // the mode `production` makes `wasm-pack` build in `release` mode.
            // TODO: We always build a production build because a development build runs slow
            // TODO: The function which is slowing it down is TileProto::decode() which maps the tile proto struct
            // TODO: into our data structure. (Development: 15s, Production: 60ms)
            forceMode: "production",

            // Controls plugin output verbosity, either 'info' or 'error'.
            // Defaults to 'info'.
            // pluginLogLevel: 'info'
        }),
    ]
});
```
