### ISSUE TITLE
CSS render delay problem

### ISSUE THREAD

**Issue by littlee** [webpack/webpack#1427]
I require all the static file in the entry.js
```js
require('a.css');
require('b.css');
// other css ...
require('a.js');
require('b.js');
// other js ...
```
and I include bundle.js in html at the bottom of body
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	//...
      <script src="bundle.js"></script>
</body>
</html>
```
when I open the page,
I will see something like this before the bundle.js is completely downloaded
![1111](https://cloud.githubusercontent.com/assets/7534668/9731213/3ac146d2-564e-11e5-8436-945dcb49c480.png)

my final page
![222](https://cloud.githubusercontent.com/assets/7534668/9731240/56608704-564e-11e5-85f2-c9b2cdf43cc5.png)

**Comment by SimenB** [comment]
You could do `ExtractTextPlugin` and have them in `head`

**Comment by littlee** [comment]
I tried the `ExtractTextPlugin`,
but I met some problem about path of font
```
build/
css/
fonts/
images/
js/
less/
page.html
```
my config file
```js
var path = require('path');
var webpack = require('webpack');
var I18nPlugin = require('i18n-webpack-plugin');
var languages = {
	'en_US': null,
	'zh_CN': require('./js/i18n/zh_CN.json')
};
var ExtractTextPlugin = require("extract-text-webpack-plugin");
module.exports = Object.keys(languages).map(function(language) {
	return {
		name: language,
		entry: {
			page: './js/page.js'
		},
		output: {
			path: path.join(__dirname, 'build'),
			filename: language + '.[name].js',
			publicPath: './build/'
		},
		module: {
			loaders: [{
				test: /\.less$/,
				loader: ExtractTextPlugin.extract("style-loader", "css-loader!less-loader")
			}, {
				test: /\.css$/,
				loader: ExtractTextPlugin.extract("style-loader", "css-loader")
			}, {
				test: /\.(ttf|eot|svg|woff(2)?)(\?v=[\d.]+)?(\?[a-z0-9#-]+)?$/,
				loader: 'file-loader'
			}, {
				test: /\.(png|jpg|gif)$/,
				loader: 'url-loader?limit=8192'
			}]
		},
		plugins: [
			new I18nPlugin(
				languages[language]
			),
			new webpack.ProvidePlugin({
				$: 'jquery',
				jQuery: 'jquery',
				'window.jQuery': 'jquery',
			}),
			new webpack.DefinePlugin({
				'require.specified': 'require.resolve'
			}),
			new ExtractTextPlugin("[name].css")
		]
	};
});
```

it generate `page.css`,
but inside this file,
it has some code like:
```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(./build/f4769f9bdb7466be65088239c12046d1.eot);
  src: url(./build/f4769f9bdb7466be65088239c12046d1.eot?#iefix) format('embedded-opentype'), url(./build/448c34a56d699c29117adc64c43affeb.woff2) format('woff2'), url(./build/fa2772327f55d8198301fdb8bcfc8158.woff) format('woff'), url(./build/e18bbf611f2a2e43afc071aa2f4e1512.ttf) format('truetype'), url(./build/f721466883998665b87923b92dea655b.svg#glyphicons_halflingsregular) format('svg');
}
```

and if I link this css file in html
```html
<link rel="stylesheet" href="build/index.css">
```
the path of fonts is wrong, how do I fix it?
Can you offer some tips about `publicPath` configuration?
