### ISSUE TITLE
asset/resource builds outside of dist when [pathname] contains references to hoisted node_modules

### ISSUE THREAD

**Issue by dreyks** [webpack/webpack#14392]
# Bug report

**What is the current behavior?**

Files located in hoisted node_modules of a workspace and loaded as `asset/resource` are built outside of dist. This differs from what `file-loader` does

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/dreyks/asset-resource-bug

**What is the expected behavior?**

All built files should end up inside the dist folder no matter where they are located on the fs

**Other relevant information:**
webpack version:  webpack@5.56.0
Node.js version: v14.13.1
Operating System: MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Interesting, because `[path]` is full path to a module, you get `../node_modules/slick-carousel/slick/fonts/slick.eot` (as relative path), but when you concat it with `output.path` (i.e. `/dist`) you will get `./dist/../node_modules/slick-carousel/slick/fonts/slick.eot`, you can fix it using:
```
module.exports = {
  context: path.resolve(__dirname, '../'),
  mode: 'development',
  entry: path.resolve(__dirname, './src/index.js'),
  output: {
    assetModuleFilename: '[path][name]-[hash][ext]'
  },
};
```

the main problem - we don't know what is `node_modules`, it is just directory, even more you can use another directory for modules (using configuration files). if we change logic we will not be able to write something above `output.path`, but some developers are doing it.

**Comment by dreyks** [comment]
the thing is i want `context` to remain `.` because that's where the app code is. the `../` crops in only because of how workspaces hoist node_modules. Additionally, as you can see from my example `file-loader` doesn't have this issue - it replaces all `..` with `_` and the path becomes `dist/_/node_modules/....`

**Comment by alexander-akait** [comment]
@dreyks yes, `file-loader` is doing it, but here limitation, you can't emit assets above `output.path` (as I said before)

**Comment by dreyks** [comment]
hmm... I see. I'll probably have to drop the `[pathname]` part as a workaround

**Comment by alexander-akait** [comment]
@dreyks yep, I see, let's wait @sokra answer, here interesting case

**Comment by alexander-akait** [comment]
@dreyks just interesting - are you using monorepos? Why do not use default values (for debug purpose)?

**Comment by dreyks** [comment]
@alexander-akait  yes, I'm using a monorepo powered by yarn workspaces. which hoist all the node_modules to the root level.

what do you mean by "default values"?

**Comment by alexander-akait** [comment]
> what do you mean by "default values"?

`[hash][ext][query]`

**Comment by dreyks** [comment]
well... I don't really remember why it was done like this (years ago). I think I'll just use the defaults now, was just surprised that webpack5 behaves differently than file-loader

**Comment by alexander-akait** [comment]
yes, there are some breaking changes between asset modules and `file-loader`

**Comment by vankop** [comment]
can we close this?

**Comment by glen-84** [comment]
I think I have exactly the same issue, but I'm using npm workspaces.

Please don't close.

**Comment by alexander-akait** [comment]
@glen-84 But, how we should fix it? Сhanging logic will be breaking change and break behavior for developer whom emitted files above `path.output`? I see only one solution `[context-relative-path]`

**Comment by glen-84** [comment]
Ya, I was thinking about another placeholder token, but wasn't sure of what it would be called.

The other direction would be to configure webpack to let it know the name of your module directory, etc.

If you're sure that developers _are_ relying on this behaviour, then I suppose a placeholder token may be the only/best option.

**Comment by glen-84** [comment]
```css
/* barlow-latin-500-normal*/
@font-face {
  font-family: "Barlow";
  font-style: normal;
  font-display: swap;
  font-weight: 500;
  src: url(http://127.0.0.1:4200/assets/fonts/../../node_modules/@fontsource/barlow/files/barlow-latin-500-normal-9d34d8c5.woff2) format("woff2"), url(http://127.0.0.1:4200/assets/fonts/../../node_modules/@fontsource/barlow/files/barlow-all-500-normal-ea42a9e8.woff) format("woff");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

You can see the double `..` here, which is why it ends up in the `public` directory.

It'd be good if these relative segments could be removed, resulting in just `/assets/fonts/node_modules/...`.
