### ISSUE TITLE
publicPath escapes '@' character while emitting css files

### ISSUE THREAD

**Issue by jedrzejowski** [webpack/webpack#15012]
# Bug report

Hi, I'm developing chrome extension and in order to use images in CSS styles i need to set `pubicPath` to `chrome-extension://__MSG_@@extension_id__/` ([see why](https://developer.chrome.com/docs/extensions/reference/i18n/)).

**What is the current behavior?**

For unknown reason CSS files are generated like this:
```css
body {
    background: red;
    background-image: url(chrome-extension://__MSG_%40@extension_id__/895c2722a512d5b2e333.png);
/*                                                 ^^^                                           */
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I prepared [repository](https://github.com/jedrzejowski/my-issue-3):
```shell
git clone git@github.com:jedrzejowski/my-issue-3.git webpack-issue-XXX
cd webpack-issue-XXX
npm ci
npx webpack
cat dist/index.css 
```

**What is the expected behavior?**

CSS file should look like this:
```css
body {
    background: red;
    background-image: url(chrome-extension://__MSG_@@extension_id__/895c2722a512d5b2e333.png);
}
```

**Other relevant information:**
webpack version:  `5.65.0`, bug was introduced in version `5.52.0` 
Node.js version: 16/17
Operating System: Linux 
Additional tools: none
