### ISSUE TITLE
load font in less file

### ISSUE THREAD

**Issue by Dreampie** [webpack/webpack#1590]
```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons');
  src: local('MaterialIcons-Regular');
  src: url('../../node_modules/material-design-icons/iconfont/MaterialIcons-Regular.woff') format('woff');
}
```

back

```javascript
module.exports = __webpack_public_path__ + "ead0f796431d02360bb912475f68f823.woff"


/*****************
 ** WEBPACK FOOTER
 ** ./~/material-design-icons/iconfont/MaterialIcons-Regular.woff
 ** module id = 207
 ** module chunks = 0
 **/
```
error

Failed to decode downloaded font: http://localhost:9001/ead0f796431d02360bb912475f68f823.woff

can't return font?
