### ISSUE TITLE
Unexpected automatic fix for invalid @import statements in wrong order.

### ISSUE THREAD

**Issue by hyf0** [webpack/webpack#16095]
# Bug report

**What is the current behavior?**

> In CSS 2.1, any `@import` rules must precede all other rules (except the `@charset` rule, if present).  [link](https://stackoverflow.com/questions/9860763/css-import-and-the-order-of-it)
- esbuild chooses to generate invalid code with warnings.
- webapck chooses to be tolerated and tries to generate correct output.

input:

![image](https://user-images.githubusercontent.com/49502170/174709903-dfdb7b38-68ee-43b1-a5b5-92a7a18af5ab.png)

# webpack output

```css
@import url(https://some/other/external/css);
@import url(https://some/external/css);
.c {
  background: red;
}

.c {
  color: yellow;
}

body {
  background: red;
}

.b {
  background: red;
}

.b {
  color: yellow;
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

input:

![image](https://user-images.githubusercontent.com/49502170/174709903-dfdb7b38-68ee-43b1-a5b5-92a7a18af5ab.png)

**What is the expected behavior?**

# esbuild output

```css
/* src/import/c.css */
.c {
  background: red;
}
@import url(https://some/other/external/css);
.c {
  color: yellow;
}

/* src/import/a.css */
body {
  background: red;
}

/* src/import/b.css */
.b {
  background: red;
}
@import url(https://some/external/css);
.b {
  color: yellow;
}

```

with warning

```
▲ [WARNING] All "@import" rules must come first [invalid-@import]

    src/import/b.css:5:0:
      5 │ @import url("https://some/external/css");
        ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    src/import/b.css:1:0:
      1 │ .b {
        ╵ ^

▲ [WARNING] All "@import" rules must come first [invalid-@import]

    src/import/c.css:5:0:
      5 │ @import url("https://some/other/external/css");
        ╵ ~~~~~~~

  This rule cannot come before an "@import" rule

    src/import/c.css:1:0:
      1 │ .c {
        ╵ ^
```

**Other relevant information:**
webpack version:  ^5.73.0
Node.js version: 
Operating System: 
Additional tools:

I just want to make sure the current behavior of webpack is intended or a UB?

**Comment by alexander-akait** [comment]
Yes, it is expected for externals `@import`, because when you concat multiple files some of them can havean an external `@import` at top and we want to support it

**Comment by hardfist** [comment]
> Yes, it is expected for externals `@import`, because when you concat multiple files some of them can havean an external `@import` at top and we want to support it

But webpack's current behavior is not spec compatible, I made an demo which shows the render result diffs between native css | webpack css | esbuild css, and native css | esbuild render result diffs with webpack's result.
you can see code here https://github.com/hardfist/css-demo.
* index.css
```css
@import url('./before.css');
.middle{
  background-color: orange;
}
@import url('./after.css');
```
* after.css
```css
.after {
  background-color: red;
}
```
* before.css
```css
.before {
  background-color: blue;
}
```
The webpack's result
```css
.before {
  background-color: blue;
}
.after {
  background-color: red;
}
.middle{
  background-color: orange;
}

head{--webpack-css-demo-webpack:\.\/src\/before\.css,\.\/src\/after\.css,\.\/src\/index\.css;}
```
The esbuild's bundle result
```css
/* src/before.css */
.before {
  background-color: blue;
}

/* src/index.css */
.middle {
  background-color: orange;
}
@import url(./after.css);

```
and the result of three scenarios
* webpack render result
![image](https://user-images.githubusercontent.com/8898718/182565110-8790689e-a1c1-44de-a132-ae42284a30f3.png)
* esbuild and native render result
![image](https://user-images.githubusercontent.com/8898718/182565288-3e8f4650-187b-4f9d-a9e0-49a4b8c10388.png)

and it seems esbuild's behavior is more compatible with browser
