### ISSUE TITLE
Webpack preload only loads js assets.

### ISSUE THREAD

**Issue by icy0307** [webpack/webpack#16876]
# Bug report

**What is the current behavior?**
The magic comment Webpack preload only loads js assets when `(/* webpackPreload: true */` is added. CSS and other assets that are required by js assets are delayed until preloaded javascript is executed.

**If the current behavior is a bug, please provide the steps to reproduce.**
await-import-by-initial-chunk.js
``` js
export async function awaitImportByInitialChunk() {
    const { awaitImportByAsyncChunk } = await import(/* webpackPreload: true */'./await-imported-by-async-chunk');
    awaitImportByAsyncChunk();
}
```
await-imported-by-async-chunk.js
``` js 
import './await-imported-by-async-chunk.css';
export async function awaitImportByAsyncChunk() {
    console.log('awaitImportByAsyncChunk');
}
```
await-imported-by-async-chunk.css
```css
@font-face {
  font-family: 'Roboto';
  font-weight: 400;
  src: url('../../../../Roboto-Regular.woff2') format('woff2'),
  url('../../../..//Roboto-Regular.woff') format('woff');
}
```

**What is the expected behavior?**
Every type of asset that link preload support can be preloaded, not being held until javascript execution.
So `await-imported-by-async-chunk.css` and the corresponding font file should be preloaded as well.

(I don't know if this is a bug or an intentional behavior) 

**Other relevant information:**
webpack version:  5.24.4
Node.js version: v19.7.0
Operating System: 
Additional tools:
