### ISSUE TITLE
experiments.css generate wrong url path

### ISSUE THREAD

**Issue by ahabhgk** [webpack/webpack#16969]
# Bug report

**What is the current behavior?**

With following webpack config:

```js
// webpack.config.js
module.exports = {
  entry: 'index.css',
  output: {
    publicPath: 'aaa.com/aa/',
  },
  module: {
    rules: [{ test: /\.png$/, type: 'asset/resource' }],
  },
  experiments: {
    css: true,
  },
}
```

```css
/* index.css */
.a {
  background-image: url(./bg.png);
}
```

will generate:

```css
.foo {
  a: url(bg.png); /* <-- wrong */
}
head{--webpack-main:\.\/index\.css;}
```

**What is the expected behavior?**

It should generate:

```css
.foo {
  a: url(aaa.com/aa/bg.png); /* <-- wrong */
}
head{--webpack-main:\.\/index\.css;}
```

**Other relevant information:**
webpack version: 5.76.3
Node.js version: 18
Operating System: osx
