### ISSUE TITLE
Setting `target` to `"browserslist:query"` seems to be ignored

### ISSUE THREAD

**Issue by Arkellys** [webpack/webpack#17584]
# Bug report

**What is the current behavior?**

When using the following configuration (or with any other query), it doesn't seem to be taken into account.

```js
{
  target: "browserslist:last 4 version",
  [...]
}
```

I'm taking the default example of [Autoprefixer](https://autoprefixer.github.io/) to test this. For these styles:

```css
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

I get:

```css
.example {
    display: grid;
    transition: all .5s;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}
```

I always get the same output regardless of the query I use after `browserslist:`

**If the current behavior is a bug, please provide the steps to reproduce.**

The full configuration I'm using is pretty much the same as [react-scripts's](https://github.com/facebook/create-react-app/blob/0a827f69ab0d2ee3871ba9b71350031d8a81b7ae/packages/react-scripts/config/webpack.config.js). You can test it by using:

```
npx create-react-app my-app
cd my-app
npm run eject
```

1. Update `config/webpack.config.js` to change the `target`
2. Remove `browserslist` from `package.json`
3. Add `<div className="example">My test box</div>` on `src/App.js`
4. Add the css above in `src/App.css`
5. Run `npm run start`

I think it's reproductible on any config though.

**What is the expected behavior?**

This is what I get when I set the configuration in `package.json` instead of `target`:

```json
{
  "browserslist": "last 4 version"
}
```

```css
.example {
    display: grid;
    -webkit-transition: all .5s;
    transition: all .5s;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background: -webkit-gradient(linear, left top, left bottom, from(white), to(black));
    background: linear-gradient(to bottom, white, black);
}
```

I expect to get the same output whether I set `browserslist` in `package.json` or `target`.

**Other relevant information:**

The query itself seems to be detected, since I get an error if I use a wrong query:
```shell
Unknown browser query `ie6`. Maybe you are using old Browserslist or made typo in query.
```

webpack version:  v5.64.4
Node.js version: v16.14.2
Operating System: Windows 10
