### ISSUE TITLE
relative resource path

### ISSUE THREAD

**Issue by memotail** [webpack/webpack#1853]
## webpack config
```javascript
{
  output: {
    path: path.join(__dirname, '../dist/assets'),
    filename: 'js/[chunkhash:8].[name].min.js',
    chunkFilename: 'js/[chunkhash:8].chunk.min.js',
    publicPath: 'assets/'
  },
  module: {
    loaders: [{
      test: /\.woff$/,
      loader: "url?limit=10000&mimetype=application/font-woff&name=fonts/[hash:8].[name].[ext]"
    }, {
      test: /\.woff2$/,
      loader: "url?limit=10000&mimetype=application/font-woff2&name=fonts/[hash:8].[name].[ext]"
    }, {
      test: /\.ttf$/,
      loader: "url?limit=10000&mimetype=application/octet-stream&name=fonts/[hash:8].[name].[ext]"
    }, {
      test: /\.eot$/,
      loader: "file?name=fonts/[hash:8].[name].[ext]"
    }, {
      test: /\.svg$/,
      loader: "url?limit=10000&mimetype=image/svg+xml&name=fonts/[hash:8].[name].[ext]"
    }, {
      test: /\.(png|jpg|gif)$/,
      loader: 'url-loader?limit=8192&name=images/[hash:8].[name].[ext]'
    }]
  }
}
```
## dist css file
```css
@font-face {
  font-family: ratchicons;
  font-weight: 400;
  font-style: normal;
  src: url(assets/fonts/2e73dee6.iconfont.eot);
  src: url(assets/fonts/2e73dee6.iconfont.eot?#iefix) format("embedded-opentype"), url(assets/fonts/f20238ea.iconfont.woff) format("woff"), url(assets/fonts/0e805a07.iconfont.ttf) format("truetype"), url(assets/fonts/6a620d2d.iconfont.svg#svgFontName) format("svg")
}
```
the error path in the web:
/dist/assets/css/assets/fonts/f20238ea.iconfont.woff 

i want to path like this:
/dist/assets/fonts/f20238ea.iconfont.woff 

## dist css file, like this
```css
@font-face {
  font-family: ratchicons;
  font-weight: 400;
  font-style: normal;
  src: url(../fonts/2e73dee6.iconfont.eot);
  src: url(../fonts/2e73dee6.iconfont.eot?#iefix) format("embedded-opentype"), url(../fonts/f20238ea.iconfont.woff) format("woff"), url(../fonts/0e805a07.iconfont.ttf) format("truetype"), url(../fonts/6a620d2d.iconfont.svg#svgFontName) format("svg")
}
```

What I do to achieve?
