### ISSUE TITLE
css class dissapears when using webpack.optimize.UglifyJsPlugin

### ISSUE THREAD

**Issue by smmoosavi** [webpack/webpack#2394]
Here is the minimal gist: https://gist.github.com/smmoosavi/b9e2f647d995be3a2da8ee1751c134e3

If you [enable the UglifyJsPlugin ](https://gist.github.com/smmoosavi/b9e2f647d995be3a2da8ee1751c134e3#file-webpack-config-js-L20:L25), the produced css file will have 2 classes instead of 3. In fact class `._1gwPWr77dmf4i5iRBt9FXY` which corresponds to the `turquoise` class is missing.

The strange thing is the sensitivity to the exact word `turquoise` in [line 7 of style.scss](https://gist.github.com/smmoosavi/b9e2f647d995be3a2da8ee1751c134e3#file-style-scss-L7) before the colon. If you change it to anything else, the problem goes away. We did found this problem with word `turquoise` in other projects we were working on.

**Comment by sokra** [comment]
@jhnns any idea?

**Comment by jhnns** [comment]
@smmoosavi looks like a (fixed) bug in node-sass to me. I've checked out the gist, ran `npm install`, uncommented the `webpack.optimize.UglifyJsPlugin` and got:

```css
._3EznytmHEEVpgvnBEe64j0{border-color:#1abc9c!important}._2UC_L9fkfDfi-7Y6HHW0zg{border-color:#16a085!important}.DD-CK8g1qlIW4R3C-upcp{border-color:#2ecc71!important}
/*# sourceMappingURL=styles.css.map*/
```

My dependencies are:

```
npm ls --depth=0
test-webpack@1.0.0 /Users/jhnns/Downloads/c3bb3b17dd00acb632889793d6f7d643
├── css-loader@0.23.1
├── extract-text-webpack-plugin@1.0.1
├── node-sass@3.6.0
├── sass-loader@3.2.0
├── style-loader@0.13.1
└── webpack@1.13.0
```

So it looks like the only thing that has changed was `node-sass`.

Just as feedback: Thanks for providing a test-case, that's better than most bug reports. But this is not a minimal test-case. It would be even more helpful, if you'd just include the things that still produce the error.

For instance, you could try to remove Sass and you'd probably see that the error is caused by Sass. This helps tracking down bugs a lot. Anyway, thanks for reporting 👍
