### ISSUE TITLE
Extract Text Plugin: require.ensure() causes incomplete file (Webpack 2)

### ISSUE THREAD

**Issue by iotch** [webpack/webpack#2450]
Hello. 
When using Extract Text Plugin with the option `allChunks: true` in conjunction with `require.ensure()`, incomplete output file being created.

Test case:

````js
// webpack.config.js

var webpack           = require('webpack');
var path              = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    context: path.join(__dirname, '.'),
    entry: {
        bundle: ['./index.js'],
    },
    output: {
        path: path.join(__dirname, './output'),
        filename: 'bundle.js',
        chunkFilename: '[name].js',
    },
    module: {
        loaders: [
            {
                test: /\.css$/,                    
                include: path.join(__dirname, '.'),
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
            },
        ],
    },
    
    plugins: [
        new ExtractTextPlugin('styles.css', {allChunks: true}),
    ]
};
````

````js
// index.js

require.ensure([], function(require) {    
    require('./moduleA.js');    
}, 'moduleA');
````

````js
// moduleA.js

import styles from './moduleA.css';
import './moduleB.js';
````

````css
/* moduleA.css */

.moduleA {
    color:red;
}
````

````js
// moduleB.js

import styles from './moduleB.css';
````

````css
/* moduleB.css */

.moduleB {
    color:blue;
}
````

Webpack's output:
````
Version: webpack 2.1.0-beta.7
Time: 1643ms
     Asset      Size  Chunks             Chunk Names
moduleA.js   2.17 kB       0  [emitted]  moduleA
 bundle.js    4.5 kB       1  [emitted]  bundle
styles.css  51 bytes    0, 1  [emitted]  moduleA, bundle
   [0] ./index.js 96 bytes {1} [built]
   [1] multi bundle 28 bytes {1} [built]
   [2] ./moduleA.js 78 bytes {0} [built]
   [5] ./moduleB.js 35 bytes {0} [built]
    + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
````

Actual `output/styles.css` contents:
````css
/* moduleB.css */

.moduleB {
    color:blue;
}
````

Expected:
````css
/* moduleA.css */

.moduleA {
    color:red;
}/* moduleB.css */

.moduleB {
    color:blue;
}
````

It seems from the webpack's output, that in case when the plugin extracts from  multiple chunks (moduleA, bundle), only the latter css file is used.
Thanks!
