### ISSUE TITLE
Using plugin  "webpack.optimize.UglifyJsPlugin" led to remove the style "display: -webkit-flex;"

### ISSUE THREAD

**Issue by hopefuture** [webpack/webpack#2543]
Thank you to review the issue.

I using this plugin to compress js and css. I found an issue. It will remove the style  "display: -webkit-flex;".

The css file

``` css
.product-grid {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  -webkit-flex-flow: wrap;
  flex-wrap: wrap;
  -ms-flex-line-pack: center;
  -webkit-align-content: center;
  align-content: center;
}
```

after webpack builded, the css will become

``` css
.product-grid {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  display: -webkit-flex;
  -webkit-flex-flow: wrap;
  flex-wrap: wrap;
  -ms-flex-line-pack: center;
  align-content: center
}
```

The result is it remove "display: -webkit-flex;".
