### ISSUE TITLE
Webpack2 + ExtractTextWebpackPlugin + Code Split produce only the last part of the css

### ISSUE THREAD

**Issue by SummerWish** [webpack/webpack#2763]
webpack 2.1.0-beta.15

Description of the demo in short:

- The project imported some stylesheets (a, b) and they are correctly extracted by ExtractTextWebpackPlugin
- The project dynamically loads a module X
- Module X imported some stylesheets (async-a, async-b) → The final css extracted from ExtractTextWebpackPlugin only contains async-b (the last imported stylesheet).

It behaviors correctly (the extracted css contains a, b, async-a, async-b) if either:

- use webpack1

or:

- only one stylesheet is imported in module X

Because it works correctly with webpack1, I think this issue is related to webpack itself and I'm reporting it here.

`webpack.config.js`:
```js
var path = require('path');
var webpack = require('webpack');

var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractProjectCSS = new ExtractTextPlugin('app.css', { allChunks: true });

var root = function (fn) {
  return path.resolve(__dirname, fn);
};

var config = {
  context: root('src'),
  entry: {
    dest: './app.js',
  },
  output: {
    path: root('dest'),
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },
  resolve: {
    modules: [root('node_modules'), root('src')],
    extensions: ['.js', ''],
  },
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: extractProjectCSS.extract(['css']),
      },
    ]
  },
  plugins: [
    extractProjectCSS,
  ],
};

module.exports = config;
```

`src/app.js`:
```js
require('./a.css');
require('./b.css');

require.ensure(['./async.js'], function (require) {
  var asyncModule = require('./async.js');
  alert(asyncModule);
});
```

`src/async.js`:
```js
require('./async-a.css');
require('./async-b.css');

module.exports = 'bar';
```

`src/a.css`:
```css
.a {
  background: #FFF;
}
```

`src/b.css`:
```css
.b {
  background: #FFF;
}
```

`src/async-a.css`:
```css
.async-a {
  background: #FFF;
}
```

`src/async-b.css`:
```css
.async-b {
  background: #FFF;
}
```

Generated `dest/app.css`:
```css
.async-b {
  background: #FFF;
}

/*# sourceMappingURL=app.css.map*/
```

Expected (webpack1):
```css
.a {
  background: #FFF;
}
.b {
  background: #FFF;
}
.async-a {
  background: #FFF;
}
.async-b {
  background: #FFF;
}

/*# sourceMappingURL=app.css.map*/
```

Note: the issue also exists if you are using the `import` and `System.import` syntax introduced in webpack2.
