### ISSUE TITLE
@import url syntax error

### ISSUE THREAD

**Issue by plaxdan** [webpack/webpack#330]
I'm getting a syntax error loading a [straight css file](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.css) (no less or sass):

``` css
@import url('font/locate-fa.woff');
@import url('css/locate-fa.css');
@import url('css/animation.css');

.leaflet-touch .leaflet-bar-part-single {
    -webkit-border-radius: 7px 7px 7px 7px;
            border-radius: 7px 7px 7px 7px;
    border-bottom: none;
}

.leaflet-control-locate a {
    font-size: 1.4em;
    margin-left: 1px;
    color: #444;
}

.leaflet-control-locate.active a {
    color: #265B86;
}

.leaflet-control-locate.active.following a {
    color: #FC8428;
}

.leaflet-touch .leaflet-control-locate {
    box-shadow: none;
    border: 2px solid rgba(0,0,0,0.2);
    background-clip: padding-box;
}
```

The error is:

``` javascript
ERROR in ./~/css-loader!./build/vendor/leaflet-locatecontrol/L.Control.Locate.css
Module build failed: SyntaxError: Unexpected token '
  at Object.parse (native)
  at extractImports (/Users/daniel/dev/ds/plugin-leaflet/node_modules/css-loader/index.js:86:47)
  at Object.module.exports (/Users/daniel/dev/ds/plugin-leaflet/node_modules/css-loader/index.js:20:17)
 @ ./build/vendor/leaflet-locatecontrol/L.Control.Locate.css 4:2-175
```

The config is:

``` javascript
module: {
    loaders: [
      {
        test: /\.gif$|\.eot$|\.jpe?g$|\.mp3$|\.png$|\.svg$|\.ttf$|\.ttf$|\.wav$|\.woff$/,
        loader: 'url-loader'
      }, {
        test: /\.scss$/,
        loader: 'style-loader!css-loader!sass-loader'
      }, {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }, {
        test: /\.coffee$/,
        loader: 'coffee-loader'
      }
    ]
  }
```

Just as with #146 I've tried `resolve.alias`, `resolve.modulesDirectories` and `resolve.fallback` without success. With #146 there was a bug in the less loader (fixed by 590d12fbc7dbf84393b75436ecd494a03dbdab6e). In my case there's no preprocessor and it's complaining about just the css syntax. Is there something I'm missing?
