### ISSUE TITLE
Having troubles resolving node_modules with main set to ./

### ISSUE THREAD

**Issue by vojtatranta** [webpack/webpack#5048]
**What is the current behavior?**
If a module such as this one https://github.com/avocode/react-resizer/blob/master/package.json
has it's `main` set to `./`. Webpack 2 seems not to be able to correctly resolve to `./index.js` event when `mainFiles` are set to `['index', 'index.js', 'index.coffee' ...]`

Webpack throws error:
```
Module not found: Error: Recursion in resolving
Stack:
  resolve: (/Users/vojtatranta/code/avocode/avocode) react-resizer
  new-resolve: (/Users/vojtatranta/code/avocode/avocode) react-resizer
  parsed-resolve: (/Users/vojtatranta/code/avocode/avocode) react-resizer module
  described-resolve: (/Users/vojtatranta/code/avocode/avocode) react-resizer module
  raw-module: (/Users/vojtatranta/code/avocode/avocode) react-resizer
  module: (/Users/vojtatranta/code/avocode/avocode) react-resizer
  resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules) ./react-resizer
  new-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules) ./react-resizer
  parsed-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules) ./react-resizer
  described-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules) ./react-resizer
  relative: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) 
  described-relative: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) 
  directory: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) 
  existing-directory: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) 
  resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) ./
  new-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) ./
  parsed-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) . directory
  described-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) . directory
  relative: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer)  directory
  described-relative: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer)  directory
  directory: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer)  directory
  existing-directory: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer)  directory
  resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) ./ directory
  new-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) ./ directory
  parsed-resolve: (/Users/vojtatranta/code/avocode/avocode/node_modules/react-resizer) . directory
 @ ./test.js 3:14-38
 @ multi ./test.js
```

**To reproduce**
Require module `react-resizer` with Webpack 2

**What is the expected behavior?**
It should resolve path to `./index.js` and properly required and bundled.

Webpack version: `2.6.1`
